title: Avinab Neogy
url: "https://avinab-neogy.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/avinab-neogy/avinab-neogy.github.io"
footer_text: "with love"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Projects"
   link: "/projects"
 - name: "Interests"
   link: "/interests"
 - name: "Writing"
   link: "/writing"
 - name: "Contact"
   link: "/contact"

theme: jekyll-theme-minimal